version: '3.8'

services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test"	
    volumes:
       - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
       - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
valumes:
    postgres_data